class AuthError(Exception):
    pass


class ConfigError(Exception):
    pass
